server:
 #error:
  #include-stacktrace:
 port: 9070
debug: false
spring:
  application:
    name: bank-account-managment
  h2:
   console:
    settings:
        web-allow-others: true
    enabled: true
logging:
  level:
    org.springframework: debug
    org.hibernate: debug